Added API for distance sensor in telemetry plugin.
mavlink/MAVSDK-Proto pull request #181
Opened 2020-10-07 11:27 UTC by hrnbot

Added API for distance sensor in telemetry plugin.

2020-10-07 12:03 UTC, julianoes commented on protos/telemetry/telemetry.proto
> +    uint64 min_distance=1; // Minimum distance the sensor can measure.
What's the unit? And what about using `float`?

2020-10-07 12:03 UTC, julianoes commented on protos/telemetry/telemetry.proto
> +    uint64 min_distance=1; // Minimum distance the sensor can measure.
And do we need multiple instances?

2020-10-07 12:10 UTC, julianoes commented on protos/telemetry/telemetry.proto
> +    uint64 min_distance=1; // Minimum distance the sensor can measure.
This is my suggestion:
```suggestion
    float min_distance_m = 1; // Minimum distance the sensor can measure.
```

And then the same for the others.

2020-10-07 12:11 UTC, julianoes commented on protos/telemetry/telemetry.proto
> +    uint64 min_distance=1; // Minimum distance the sensor can measure.
And you could make it a repeated field, one entry per `id` in https://mavlink.io/en/messages/common.html#DISTANCE_SENSOR.

2020-10-07 17:12 UTC, JonasVautherin requested changes
A few small suggestions, if that's fine for you :innocent:.

2020-10-07 17:12 UTC, JonasVautherin commented on protos/telemetry/telemetry.proto
> +}
```suggestion
message DistanceSensor {
    float min_distance = 1; // Minimum distance the sensor can measure.
    float max_distance = 2; // Maximum distance the sensor can measure.
    float current_distance = 3; // Current distance reading.
}
```

2020-10-07 17:12 UTC, JonasVautherin commented on protos/telemetry/telemetry.proto
> +
```suggestion
```

2020-10-10 06:32 UTC, julianoes commented on protos/telemetry/telemetry.proto
> +    float current_distance = 3; // Current distance reading.
```suggestion
    float minimum_distance_m = 1 [(mavsdk.options.default_value)="NaN"]; // Minimum distance the sensor can measure, NaN if unknown.
    float maximum_distance = 2 [(mavsdk.options.default_value)="NaN"]; // Maximum distance the sensor can measure, NaN if unknown.
    float current_distance_m = 3 [(mavsdk.options.default_value)="NaN"]; // Current distance reading, NaN if unknown.
```

2020-10-12 07:29 UTC, julianoes approved these changes
Looking good, thanks @hrnbot!

2020-10-12 07:29 UTC, merged