Transponder: add tslc in AdsbVehicle
mavlink/MAVSDK-Proto pull request #280
Opened 2022-04-06 09:44 UTC by chep

related to https://github.com/mavlink/MAVSDK/pull/1730

2022-04-06 09:52 UTC, JonasVautherin approved these changes

2022-04-06 09:55 UTC, JonasVautherin requested changes
> protos/transponder/transponder.proto:68:9:"uint8_t" is not defined.

Actually it seems like uint8_t is not supported in protobuf.

2022-04-06 09:55 UTC, JonasVautherin commented on protos/transponder/transponder.proto
> +	uint8_t tslc = 14; // Time Since Last Communication.
```suggestion
    uint8_t tslc = 14; // Time since last communication.
```

2022-04-06 10:03 UTC, chep commented on protos/transponder/transponder.proto
> +	uint8_t tslc = 14; // Time Since Last Communication.
fixed

2022-04-06 14:24 UTC, merged

2022-04-07 21:49 UTC, julianoes commented on protos/transponder/transponder.proto
> +    uint32 tslc = 14; // Time Since Last Communication.
What's the unit?