info: add protocol capabilities to the Info plugin
mavlink/MAVSDK-Proto pull request #301
Opened 2022-11-14 17:35 UTC by TSC21

We were missing a way to obtain the autopilot protocol capabilities on the Info plugin,

2022-11-14 20:39 UTC, JonasVautherin reviewed
This is exposing MAVLink at a pretty low level, isn't it?

Isn't this something that should be handled in the MAVSDK implementation, instead of exposed in the MAVSDK API?

@julianoes do you have an opinion?

2022-11-14 20:43 UTC, TSC21 commented
> Isn't this something that should be handled in the MAVSDK implementation, instead of exposed in the MAVSDK API?

I don't disagree, but how would you expose it higher level then? Process the bitmap entries at the implementation level and then expose the resulting capabilities as boolean flags or something? I just went through the simplest process here.

2022-11-15 11:42 UTC, JonasVautherin commented
For instance the `mission` plugin is supposed to take care of the mission protocol, so the user should not have to do anything with `PROTOCOL_CAPABILITY_MISSION_FLOAT` or `PROTOCOL_CAPABILITY_MISSION_INT` (actually what would they do with this info?).

If I take e.g. `PROTOCOL_CAPABILITY_FLIGHT_TERMINATION`, then I guess that `action->terminate()` could check that flag and return an `UNSUPPORTED` result (right now probably it just times out).

So maybe I can ask this: which flag are you planning to use, and how?

2022-11-15 11:45 UTC, TSC21 commented
> For instance the `mission` plugin is supposed to take care of the mission protocol, so the user should not have to do anything with `PROTOCOL_CAPABILITY_MISSION_FLOAT` or `PROTOCOL_CAPABILITY_MISSION_INT` (actually what would they do with this info?).
> 
> If I take e.g. `PROTOCOL_CAPABILITY_FLIGHT_TERMINATION`, then I guess that `action->terminate()` could check that flag and return an `UNSUPPORTED` result (right now probably it just times out).
> 
> So maybe I can ask this: which flag are you planning to use, and how?

Right now, the the MAVLink test suite, I have to check the following capabilities:

- `MAV_PROTOCOL_CAPABILITY_COMMAND_INT`
- `MAV_PROTOCOL_CAPABILITY_MISSION_FENCE`
- `MAV_PROTOCOL_CAPABILITY_MISSION_RALLY`

And might have to expand to others.

2022-11-15 11:53 UTC, JonasVautherin commented
> it purely uses passthough

And can't you access those capabilities from passthrough?

2022-11-15 12:01 UTC, TSC21 commented
> > it purely uses passthough
> 
> And can't you access those capabilities from passthrough?

Technically I could, but there's a conceptual difference in the usage: on the test suite, passthrough is used to validate if a certain message is being received at a certain rate (this means that the autopilot is sending that data, and we validate it). The passthrough is not used to fetch data to setup the tests, is used during the tests themselves. We before had these capabilities exposed through the `get_autopilot_version_data()` function, and that function was part of the mavsdk::system, and now we don't have it anymore.

2022-11-15 12:27 UTC, JonasVautherin commented
@julianoes what's your opinion there?

2022-11-16 01:06 UTC, JonasVautherin commented
@TSC21 for the record, didn't you say that you could access that fairly easily from mavlink-passthrough?

2022-11-18 00:31 UTC, julianoes requested changes
I don't think it makes sense to expose this. It's as @JonasVautherin said "more of a MAVLink internal thing", exactly the sort of thing that a user of MAVLink should not have to think about.

I think that testing that the internals of MAVLink are working correctly is not a primary use case of MAVSDK, and so I would probably use MAVLink passthrough for that.

2022-11-18 00:31 UTC, julianoes commented on protos/info/info.proto
> +        PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST = 0x00020000; // Parameter protocol uses C-cast of parameter values to set the param_value (float) fields: https://mavlink.io/en/services/parameter.htm
Pretty sure this does not work with the auto-generation. The only way to make this work is to change how the auto-generation works, or add boolean flags for each of the flags.

2023-01-12 21:57 UTC, julianoes commented
Closing as this does not work and it's not the intent to leak these MAVLink internal flags in the API. It would make more sense to use MAVLinkPassthrough for this.

2023-01-12 21:57 UTC, closed without merging