add more camera video stream info
mavlink/MAVSDK-Proto pull request #330
Opened 2024-02-22 08:55 UTC by tbago

The camera proto video stream info contain more detail about the stream info, so the camera server proto need use the same video stream info define;
 
the camera can have multi lens (one Visible light one Infrared). So need support multi video stream info;

2024-02-22 08:58 UTC, tbago commented
The pull request to MAVSDK will come soon

2024-05-28 06:47 UTC, julianoes requested changes

2024-05-28 06:47 UTC, julianoes commented on protos/camera/camera.proto
> +    };
The capture flags should only be internally used. They should not be visible to the user. And if we need to expose specific ones, then they have to just be boolean flags.

2024-05-28 06:47 UTC, julianoes commented on protos/camera/camera.proto
> +        11;  // Camera definition URI (http or mavlink ftp)
This is also only to be used internally.

2024-05-28 06:47 UTC, julianoes commented on protos/camera/camera.proto
> +    repeated VideoStreamInfo video_stream_infos = 1; // Video stream infos
How does this work when it's repeated? Do you get multiple video stream infos, one per video stream?

2024-12-24 06:42 UTC, closed without merging