added download function for geofence and rallypoints
mavlink/MAVSDK-Proto pull request #353
Opened 2024-09-26 07:11 UTC by mattes-bru

2024-09-26 07:39 UTC, julianoes requested changes
See suggestions. The naming must be consistent, otherwise the auto-generation won't work. Best to test it before making the PR.

However, you probably can re-use the actual mission items in the requests, e.g.:

```
message DownloadGeofenceRequest {}
message DownloadGeofenceResponse {
    MissionRawResult mission_raw_result = 1;
    repeated MissionItem geofence_items = 2; // The geofence items
}
```

2024-09-26 07:39 UTC, julianoes commented on protos/mission_raw/mission_raw.proto
> +    rpc DownloadGeofence(DownloadMissionRequest) returns(DownloadMissionResponse) {}
```suggestion
    rpc DownloadGeofence(DownloadGeofenceRequest) returns(DownloadGeofenceResponse) {}
```

2024-09-26 07:39 UTC, julianoes commented on protos/mission_raw/mission_raw.proto
> +     * Download a list of raw mission items from the system (asynchronous).
```suggestion
     * Download a list of raw geofence items from the system (asynchronous).
```

2024-09-26 07:39 UTC, julianoes commented on protos/mission_raw/mission_raw.proto
> +     * Download a list of raw mission items from the system (asynchronous).
```suggestion
     * Download a list of raw rally items from the system (asynchronous).
```

2024-09-26 07:39 UTC, julianoes commented on protos/mission_raw/mission_raw.proto
> +     rpc DownloadRallypoints(DownloadMissionRequest) returns(DownloadMissionResponse) {}
```suggestion
     rpc DownloadRallypoints(DownloadRallypointsRequest) returns(DownloadRallypointsResponse) {}
```

2024-09-26 09:29 UTC, mattes-bru commented
Sorry, I was too fast on the PR button. I updated naming & comments

2024-09-30 02:07 UTC, julianoes approved these changes

2024-09-30 02:15 UTC, merged